{% set version = "0.15.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rayimage
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rayimage_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rayimage/rayimage_{{ version }}.tar.gz
  sha256: 95a00ddd0e8da1245fd1d52aa6e5d3a3d4b8eacf6310bb2be51c5ccf9de3ad08

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-gridextra
    - r-jpeg
    - r-png
    - r-progress
    - r-rcpp
    - r-rcpparmadillo
    - r-tiff
  run:
    - r-base
    - r-gridextra
    - r-jpeg
    - r-png
    - r-progress
    - r-rcpp
    - r-rcpparmadillo
    - r-tiff

test:
  commands:
    - $R -e "library('rayimage')"           # [not win]
    - "\"%R%\" -e \"library('rayimage')\""  # [win]

about:
  home: https://www.rayimage.dev
  dev_url: https://github.com/tylermorganwall/rayimage
  license: GPL-3.0-only
  summary: Uses convolution-based techniques to generate simulated camera bokeh, depth of field, and other camera effects, using an image and an optional depth map. Accepts both filename inputs and in-memory array representations of images and matrices. Includes functions to perform 2D convolutions, reorient and resize images/matrices,
    add image overlays, generate camera vignette effects, and add titles to images.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
