{% set version = "0.11.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rayimage
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rayimage_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rayimage/rayimage_{{ version }}.tar.gz
  sha256: aada00b0d6b6dda53c6d958fa469360e03f71d4f89e2032d2c6ed207974bd214

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-gridextra
    - r-jpeg
    - r-png
    - r-progress
    - r-rcpp
    - r-rcpparmadillo
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-gridextra
    - r-jpeg
    - r-png
    - r-progress
    - r-rcpp
    - r-rcpparmadillo

test:
  commands:
    - $R -e "library('rayimage')"           # [not win]
    - "\"%R%\" -e \"library('rayimage')\""  # [win]

about:
  home: https://www.rayimage.dev
  dev_url: https://github.com/tylermorganwall/rayimage
  license: GPL-3.0-only
  summary: Uses convolution-based techniques to generate simulated camera bokeh, depth of field, and other camera effects, using an image and an optional depth map. Accepts both filename inputs and in-memory array representations of images and matrices. Includes functions to perform 2D convolutions, reorient and resize images/matrices,
    add image overlays, generate camera vignette effects, and add titles to images.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
